openline-ai/openline-cli

- scripts/install_go.sh
- scripts/install_node.sh
Describe the big picture of your changes here.  If it fixes a bug or resolves a feature request, be sure to link that issue!
Does this change impact front end code?
> update bash scripts

- scripts/install_go.sh
- scripts/install_node.sh
Describe the big picture of your changes here.  If it fixes a bug or resolves a feature request, be sure to link that issue!
Does this change impact front end code?
> Script fixes

- src/commands/dev/index.ts
Describe the big picture of your changes here.  If it fixes a bug or resolves a feature request, be sure to link that issue!
Does this change impact front end code?
> added open desktop

- .gitignore
- src/commands/dev/start.ts
- src/config/dev.ts
- src/lib/dev/deploy.ts
- src/lib/dev/installContacts.ts
- src/lib/dev/installCustomerOs.ts
- src/lib/dev/setupFiles.ts
Added support for Contacts app.  Also refactored some code.
> 51 contacts app

- src/commands/dev/rm.ts
- src/config/dev.ts
- src/lib/dev/auth.ts
- src/lib/dev/deploy.ts
Add fusionauth loadbalancer to `dev start` and `dev rm` commands
> add fustionauth loadbalancer config

- package.json
- src/commands/dev/start.ts
- src/lib/dev/auth.ts
- src/lib/dev/colima.ts
Checks to ensure kubectl context is set to `colima` before trying to install namespace.
> 86 unable to create namespace from openline namespace

- package.json
- src/commands/dev/rm.ts
- src/commands/dev/start.ts
- src/lib/dev/colima.ts
Bug fix to always ensure colima context is set before issuing command.
> context switch

- src/commands/dev/clone.ts
- src/commands/dev/rm.ts
- src/lib/dev/auth.ts
- src/lib/dev/colima.ts
- src/lib/dev/delete.ts
- src/lib/dev/neo4j.ts
- src/lib/dev/postgres.ts
Moved command logic to case statements
Improved error handling
> 92 refactor dev rm

- src/config/dev.ts
Use new location of cypher file to provision neo4j DB
> New location for cypher file

- install.sh
Add install script for mac & linux
> Add install script for mac & linux

- package.json
Added s3 bucket to package.json
> autoupdate

- packages/cli/src/lib/dev/postgres.ts
- packages/cli/src/lib/dev/voice.ts
> 231 dont wait for message store to start before provisioning cli 1

- packages/cli/src/commands/dev/rm.ts
- packages/cli/src/commands/dev/start.ts
- packages/cli/src/config/dev.ts
- packages/cli/src/lib/dev/eventstore.ts
> Added event store to openline cli

- packages/cli/src/commands/dev/ping.ts
- packages/cli/src/commands/dev/rm.ts
- packages/cli/src/commands/dev/start.ts
- packages/cli/src/config/dev.ts
- packages/cli/src/lib/dev/customer-os.ts
> 245 events processing platform

- packages/cli/src/commands/dev/ping.ts
- packages/cli/src/commands/dev/rm.ts
- packages/cli/src/commands/dev/start.ts
- packages/cli/src/config/dev.ts
- packages/cli/src/lib/dev/customer-os.ts
> Added validation api to CLI

- packages/cli/src/lib/dev/neo4j.ts
> Neo4j upgrade 4 to 5

- packages/cli/package.json
> Version Bump For Neo4j and Event Processing Platform and Validation Api 

- packages/cli/package.json
- packages/cli/src/lib/dev/neo4j.ts
> Neo4j helm fix for chart updates

- packages/cli/src/commands/dev/ping.ts
- packages/cli/src/commands/dev/rm.ts
- packages/cli/src/commands/dev/start.ts
- packages/cli/src/config/dev.ts
- packages/cli/src/lib/dev/customer-os.ts
- packages/cli/src/lib/dev/eventstore.ts
- packages/cli/src/lib/dev/jaeger.ts
> 260 jaeger implementation for local

- packages/cli/package.json
> Jaeger version bump

- packages/cli/package.json
> Added p-timeout dependency in package.

- packages/cli/package.json
- packages/cli/yarn.lock
> chore: bump npm deps

- packages/cli/package.json
- packages/cli/yarn.lock
> chore: fix moderate vulns

- packages/cli/package.json
- packages/cli/yarn.lock
> Fix new npm vulns

- packages/cli/package.json
- packages/cli/src/commands/dev/remove.ts
- packages/cli/src/lib/dev/colima.ts
- packages/cli/src/lib/dev/k3d.ts
> 288 colima removal

- packages/cli/src/commands/dev/rm.ts
- packages/cli/src/commands/dev/start.ts
- packages/cli/src/config/dev.ts
- packages/cli/src/lib/dev/postgres.ts
- packages/cli/src/lib/dev/redis.ts
- packages/cli/src/lib/dev/start.ts
> install redis

- packages/cli/src/lib/dev/jaeger.ts
> 293 jaeger version update

- packages/cli/package.json
- packages/cli/src/commands/dev/ping.ts
- packages/cli/src/commands/dev/rm.ts
- packages/cli/src/commands/dev/start.ts
- packages/cli/src/config/dev.ts
- packages/cli/src/lib/dev/customer-os.ts
> 298 user admin addition

- packages/cli/package.json
- packages/cli/src/lib/dev/jaeger.ts
> [300] updated jaeger version to latest

- packages/cli/src/lib/dev/neo4j.ts
- resources/demo-tenant.json
> [303-demo-tenant] - demo-tenant provisioning

- packages/cli/package.json
> [307-cli-ver-increase]] - version increment

- packages/cli/yarn.lock
> [316] - high vulnerability fix for npm-get-func-name

- packages/cli/package.json
- packages/cli/src/config/dev.ts
- packages/cli/src/lib/dev/eventstore.ts
> 318 event store for linux

- deployment/infra/k8s/settings-api.yaml
- packages/cli/package.json
- packages/cli/src/config/dev.ts
- packages/cli/src/lib/dev/customer-os.ts
> [COS-606] - fixed deployments paths

- packages/cli/package.json
- packages/cli/src/lib/dev/namespace.ts
> [COS-608] - fixed namespace path

- packages/cli/package.json
- packages/cli/src/lib/dev/customer-os.ts
- packages/cli/src/lib/dev/eventstore.ts
- packages/cli/src/lib/dev/jaeger.ts
- packages/cli/src/lib/dev/neo4j.ts
- packages/cli/src/lib/dev/postgres.ts
- packages/cli/src/lib/dev/redis.ts
> [COS-610] - fixed remaining paths

- packages/cli/package.json
- packages/cli/src/helpers/downloadChecker.ts
- packages/cli/src/lib/dev/customer-os.ts
- packages/cli/src/lib/dev/eventstore.ts
- packages/cli/src/lib/dev/neo4j.ts
- packages/cli/src/lib/dev/postgres.ts
- packages/cli/src/lib/dev/redis.ts
> [COS-630] - improved the wait mechanisms

- packages/cli/src/config/dev.ts
- packages/cli/src/lib/dev/deploy.ts
> [COS-624] - enable FE tests

- deployment/scripts/neo4j/customer-os.cypher
> new neo4j indexes

- packages/cli/package.json
> [COS-1022] - version bump for new demo tenant

- deployment/infra/k8s/customer-os-webhooks-loadbalancer.yaml
- deployment/infra/k8s/customer-os-webhooks-service.yaml
- deployment/infra/k8s/customer-os-webhooks.yaml
- packages/cli/src/commands/dev/ping.ts
- packages/cli/src/commands/dev/rm.ts
- packages/cli/src/commands/dev/start.ts
- packages/cli/src/config/dev.ts
- packages/cli/src/lib/dev/customer-os.ts
> [COS-1267] - webhooks

- deployment/infra/k8s/events-processing-platform.yaml
- packages/cli/src/lib/dev/neo4j.ts
- resources/demo-tenant.json
> [COS-1288] - contracts fix

- resources/demo-tenant.json
> [COS-1458] - Onboarding

- deployment/scripts/neo4j/customer-os.cypher
> Add new indexes

- packages/cli/package.json
> [COS-1524] - ver. bump

- packages/cli/package.json
- packages/cli/src/lib/dev/demo-tenant.json
> [COS-1826] - added invoicing in CLI

- packages/cli/package.json
- packages/cli/src/lib/dev/customer-os.ts
- packages/cli/src/lib/dev/neo4j.ts
> [COS-2158] - enhanced logging

- packages/cli/package.json
> [COS-2286] - release CLI

- packages/cli/package.json
> bump version for release

- packages/cli/package.json
- packages/cli/src/config/dev.ts
- packages/cli/src/lib/dev/temporal-server.ts
> remove local temporal cli install for linux

- release.sh
> add release shell script

- packages/cli/package.json
- packages/cli/src/lib/dev/temporal-server.ts
- release.sh
> improve temporal setup waiting checks
